### ISSUE TITLE
Is it possible to select the voice beside the language?

### ISSUE THREAD

**Issue by ptykamikaze** [Shmarkus/cordova-plugin-nuance-speechkit#3] opened 2018-09-13 17:10 UTC
In the [nuance's website](https://developer.nuance.com/public/index.php?task=supportedLanguages) you can select the language and the voice so I was trying to find something in the documentation that describe how can I select the voice (if it is possible)

**Comment by Shmarkus** [comment] 2018-09-14 06:49
Hello, thanks for your feedback! I belive it is possible to do it in the SDK but not in the plugin at the moment. I can implement it, if you are willing to test

**Comment by ptykamikaze** [comment] 2018-09-17 14:40
Hello! Yes! I'm willing to test this.

**Comment by Shmarkus** [comment] 2018-09-17 18:39
Very good. Are you using the plugin through Ionic or via cordova?

**Comment by ptykamikaze** [comment] 2018-09-17 18:48
Through Ionic

**Comment by Shmarkus** [comment] 2018-09-23 19:04
Thanks for the info. The implementation is in progress, but I'll be away for a week, so no progress in the next week.

**Comment by Shmarkus** [comment] 2018-10-04 19:44
Hi, the voice parameter is added in version 2.0.0. The sample app is updated to reflect these changes. **The caveat here is ionic-native, which takes time to approve pull requests**. The pull request to watch is https://github.com/ionic-team/ionic-native/pull/2761 

If you are eager to check it out now, I can send the compiled code (or you can clone *https://github.com/Shmarkus/ionic-native* repository and build the distribution package. from there, copy *dist/@ionic-native/speechkit* to your projects *node_modules/@ionic-native/speechkit*

**Comment by Shmarkus** [comment] 2018-10-04 19:55
Please note that IOS is currently untested.

**Comment by Shmarkus** [comment] 2018-10-13 16:25
Ionic pull request merged

**Comment by ptykamikaze** [comment] 2018-10-29 01:49
Thank you

**Comment by ptykamikaze** [comment] 2018-10-29 18:37
While trying to compile the iOS version, I'm getting this error:

......./Plugins/cordova-plugin-nuance-speechkit/CDVSpeechKit.m:32:43: No visible @interface for 'SKSession' declares the selector 'speakString:withLanguage:withVoice:delegate:'

in the file CDVSpeechKit.m, in this piece of code

```
    SKTransaction* transaction = [session speakString:[command.arguments objectAtIndex:0]
                                         withLanguage:[command.arguments objectAtIndex:1]
                                         withVoice:[command.arguments objectAtIndex:2]
                                             delegate:self];
```

**Comment by ptykamikaze** [comment] 2018-10-29 18:48
I have a very basic knowledge about using xcode and I have changed the file SKSession.h adding the missing `withVoice` parameter to the interface... Now I can compile but the audio is not playing so I will wait for you :) thanks 4 your support

**Comment by Shmarkus** [comment] 2018-10-29 19:57
Yes, this won't work like that. The problem is that the session allows only either withLanguage or withVoice. I'll look into that. The most promising solution is [to use options](https://developer.nuance.com/public/Help/SpeechKitFrameworkReference_iOS/Classes/SKSession.html#//api/name/speakMarkup:withLanguage:options:delegate:)

**Comment by ptykamikaze** [comment] 2018-10-29 20:00
oh OK...  thanks for your support

**Comment by Shmarkus** [comment] 2018-10-29 20:26
@ptykamikaze could you please try on IOS, replace the following in CDVSpeechKit.m:
```objective-c
- (void) startTTS:(CDVInvokedUrlCommand*)command{

    NSLog(@"CDVSpeechKit.startTTS: Entered method.");
    // If the voice is nil, use language default voice. If the voice is set, ignore language and use voices default lang.
    if (command.arguments objectAtIndex:2 == nil) {
        SKTransaction* transaction = [session speakString:[command.arguments objectAtIndex:0]
                                             withLanguage:[command.arguments objectAtIndex:1]
                                             delegate:self];
    } else {
        SKTransaction* transaction = [session speakString:[command.arguments objectAtIndex:0]
                                             withVoice:[command.arguments objectAtIndex:2]
                                             delegate:self];
    }
    NSLog(@"CDVSpeechKit.startTTS: Leaving method.");
}
```

Note that this will either use selected language when voice parameter is null, or if voice is set **it will ignore the language parameter, and use voices language instead!**

**Comment by ptykamikaze** [comment] 2018-10-29 20:32
Error CDVSpeechKit.m:33:49: Expected ']'... 

I changed that line from `if (command.arguments objectAtIndex:2 == nil) {` to `if ([command.arguments objectAtIndex:2] == nil) {` and it is working!

**Comment by ptykamikaze** [comment] 2018-10-29 20:33
Thanks a lot for your help! I thought that language and voice parameters were required

**Comment by Shmarkus** [comment] 2018-10-30 08:58
Thanks for the response! I try to create the fix today!

**Closed as completed** 2018-10-30 18:32 UTC
Labels: enhancement
